import eslint from '@eslint/js';
import { defineConfig } from 'eslint/config';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default defineConfig(
  eslint.configs.recommended,
  tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: {
      // we only run in node, not browser
      globals: globals.node,
      // required to use tseslint.configs.recommendedTypeChecked
      parserOptions: {
        projectService: true,
        // ensures the tsconfig path resolves relative to this file
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // Change typescript-eslint unsafe rules from errors to warnings
      // This allows code to pass linting while providing useful type-safety feedback
      '@typescript-eslint/no-unsafe-assignment': 'warn',
      '@typescript-eslint/no-unsafe-call': 'warn',
      '@typescript-eslint/no-unsafe-member-access': 'warn',
      '@typescript-eslint/no-unsafe-argument': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
    },
  },
  {
    ignores: [
      // generated by `vitest --coverage`
      'coverage/**',
    ],
  }
);
